@echo off
echo Starting Grocito Email Service...
cd email-service
echo Installing dependencies if needed...
if not exist node_modules npm install
echo Starting email service on port 3001...
node server.js
pause